[#ftl]
[#include "/org/openurp/webapp/apps/party/wenming/comm.ftl"/]
[@b.head/]
[@b.toolbar title="优秀项目信息"]bar.addBack();[/@]
[@b.form action="!save" theme="list"]
  [@b.field label="申请人"]${goodPerson.submitBy.fullname!"&nbsp;"}(${goodPerson.submitBy.name!"&nbsp;"})[/@]
  [@b.field label="申请时间"]${goodPerson.submitAt?date}[/@]
  [@b.field label="名称"]${goodPerson.name!"&nbsp;"}[/@]
  [@b.field label="时间"]${goodPerson.beginOn?date}~${goodPerson.endOn?date}[/@]
  [@b.field label="事迹"]${(goodPerson.statements)!"&nbsp;"}[/@]
  [@b.field label="联系人"]${(goodPerson.contactPerson)!!"&nbsp;"}[/@]
  [@b.field label="联系电话"]${(goodPerson.contactPhone)!!"&nbsp;"}[/@]
  [@b.field label="相关支撑材料"]
    &nbsp;
    [#if goodPerson.attachment??]
    [@b.a target="_blank" href="../attachment?path=${goodPost.attachment.filePath}&name=${goodPost.attachment.name?url('utf-8')}"]${(goodPost.attachment.name)!}[/@]</p>
    [/#if]
  [/@]
[/@]
[@b.foot/]