[#ftl]
[#include "/org/openurp/webapp/apps/party/wenming/comm.ftl"/]
[@b.head/]
[@b.grid  items=goodPosts var="goodPost"]
  [@b.gridbar]
    [#if editable]
    bar.addItem("审核",action.edit());
    [/#if]
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="50%" property="name" title="项目名称" align="left"][@b.a href="!info?id=${goodPost.id}"]${goodPost.name}[/@][/@]
    [@b.col width="20%" property="department.name" title="选送单位"][/@]
    [@b.col width="15%" property="attachment.name" title="详细材料"]
      [#if goodPost.attachment??]
        [@b.a target="_blank" href="../attachment?path=${goodPost.attachment.filePath}&name=${goodPost.attachment.name?url('utf-8')}"]下载[/@]
      [/#if]
    [/@]
    [@b.col width="15%" property="state.description" title="审核情况"][/@]
  [/@]
[/@]
[@b.foot/]