[#ftl]
[@b.head/]
[#include "/org/beangle/ems/security/web/action/status.ftl"/]
[#include "/org/openurp/webapp/apps/party/wenming/comm.ftl"/]

[@b.grid  items=assessItems var="assessItem" sortable="false"]
  [@b.gridbar]
    [#if Parameters['schema.id']?? && Parameters['schema.id'] != ""]
    bar.addItem("${b.text("action.new")}",action.add());
    [/#if]
    bar.addItem("${b.text("action.modify")}",action.edit());
    bar.addItem("${b.text("action.delete")}",action.remove("确认删除?"));
  [/@]
  [@b.row]
    [@b.boxcol /]
    [@b.col width="20%" property="name" title="批次名称"][@b.a href="!info?id=${assessItem.id}"]${assessItem.name}[/@][/@]
    [@b.col width="15%" property="beginOn" title="测评开始时间"]${(assessItem.beginOn?datetime)!}[/@]
    [@b.col width="15%" property="endOn" title="测评结束时间"]${(assessItem.endOn?datetime)!}[/@]
    [@b.col width="15%" property="voteBeginOn" title="投票开始时间"]${(assessItem.voteBeginOn?datetime)!}[/@]
    [@b.col width="15%" property="voteEndOn" title="投票结束时间"]${(assessItem.voteEndOn?datetime)!}[/@]
    [@b.col width="10%" property="createdAt" title="common.createdAt"]${(assessItem.createdAt?date)!}[/@]
    [@b.col width="10%" property="enabled" title="是否有效"][@c.enabled assessItem.enabled/][/@]
  [/@]
[/@]
[@b.foot/]