[#ftl]
[@b.head/]
[#include "/org/beangle/ems/security/web/action/status.ftl"/]
[#include "/org/openurp/webapp/apps/party/wenming/comm.ftl"/]

[@b.grid  items=mutualAssesss var="mutualAssess" sortable="false"]
  [@b.gridbar]
  [/@]
  [@b.row]
    [@b.col width="25%" property="department.name" title="被测评单位"]
      [@b.a href="!info?session.id=${mutualAssess.session.id}&schema.id=${mutualAssess.schema.id}"]${mutualAssess.department.name}[/@]
    [/@]
    [@b.col width="25%" property="assessDepartment.name" title="测评单位"][/@]
    [@b.col width="15%" property="assessBy.name" title="测评人员"]${mutualAssess.assessBy.fullname}（${mutualAssess.assessBy.name}）[/@]
    [@b.col width="10%" property="assessAt" title="测评提交时间"]${mutualAssess.assessAt?date}[/@]
    [@b.col width="10%" property="totalScore" title="测评总分值"][/@]
    [@b.col width="15%" property="state.description" title="状态"][/@]
  [/@]
[/@]
[@b.foot/]