[#ftl]
[@b.head/]
[@b.toolbar title="加分项目编辑"]bar.addBack();[/@]
[@b.tabs]
  [@b.tab label="加分项目信息"]
    [@b.form action="!save" title="基本信息" theme="list"]
      [@b.textfield name="assessBonusType.name" label="加分项目类别" value="${assessBonusType.name!}" required="true" maxlength="50"/]
    [/@]
  [/@]
[/@]
[@b.foot/]