[#ftl]
[#include "/org/openurp/webapp/apps/party/wenming/comm.ftl"/]
[@b.head/]
[@b.toolbar title="文明示范岗信息"]bar.addBack();[/@]
[@b.form action="!save" theme="list"]
  [@b.field label="申请人"]${goodPost.submitBy.fullname!"&nbsp;"}(${goodPost.submitBy.name!"&nbsp;"})[/@]
  [@b.field label="申请时间"]${goodPost.submitAt?date}[/@]
  [@b.field label="项目名称"]${goodPost.name!"&nbsp;"}[/@]
  [@b.field label="投票开始结束时间"]${goodPost.beginOn?date}~${goodPost.endOn?date}[/@]
  [@b.field label="申报理由"]${(goodPost.statements)!"&nbsp;"}[/@]
  [@b.field label="项目方案"]${(goodPost.plan)!!"&nbsp;"}[/@]
  [@b.field label="特色与创新点"]${(goodPost.features)!!"&nbsp;"}[/@]
  [@b.field label="联系人"]${(goodPost.contactPerson)!!"&nbsp;"}[/@]
  [@b.field label="联系电话"]${(goodPost.contactPhone)!!"&nbsp;"}[/@]
  [@b.field label="相关支撑材料"]
    &nbsp;
    [#if goodPost.attachment??]
    [@b.a target="_blank" href="../attachment?path=${goodPost.attachment.filePath}&name=${goodPost.attachment.name?url('utf-8')}"]${(goodPost.attachment.name)!}[/@]</p>
    [/#if]
  [/@]
[/@]
[@b.foot/]